// src/ui/i18n.ts
// Lightweight, dependency-free i18n for the UI chrome. Keyed dictionaries keep
// it readable and i18next-migratable: a new locale is one more object, and the
// t(key, params) call sites would survive a future library swap. The game LOG
// is intentionally NOT translated here (it is generated by the engine).
import { createContext, createElement, useContext, useState, type ReactNode } from 'react';
import type { Resource } from '../engine/types';

export type Lang = 'en' | 'ko';
export const LANGS: Lang[] = ['en', 'ko'];
export type Params = Record<string, string | number>;

const dict: Record<Lang, Record<string, string>> = {
  en: {
    'newgame.title': 'Hexland — New Game',
    'newgame.disclaimer': 'Unofficial fan project. Not affiliated with or endorsed by Catan GmbH / Catan Studio.',
    'newgame.aiOpponents': 'AI opponents:',
    'newgame.difficulty': 'Difficulty:',
    'diff.easy': 'Easy',
    'diff.medium': 'Normal',
    'diff.hard': 'Hard',
    'diff.impossible': 'Impossible',
    'newgame.seed': 'Seed:',
    'newgame.start': 'Start',

    'action.roll': '🎲 Roll',
    'action.road': 'Road',
    'action.settlement': 'Settlement',
    'action.city': 'City',
    'action.buyDev': 'Buy Dev',
    'action.playDev': 'Play Dev',
    'action.trade': 'Trade',
    'action.endTurn': 'End Turn',

    'app.newGame': '↩ New Game',
    'app.setupSettlement': 'Setup: place your settlement (click a highlighted spot).',
    'app.setupRoad': 'Setup: place your road (click a highlighted spot).',
    'app.moveRobber': 'Move the robber: click a highlighted hex.',
    'app.tradeOffer': '{name} offers a trade.',
    'app.accept': 'Accept',
    'app.decline': 'Decline',
    'app.wins': '{name} wins! 🏆',
    'app.playAgain': 'New Game',

    'player.you': 'You',
    'player.ai': 'AI {n}',
    'player.vp': '{n} VP',
    'player.cards': 'cards: {n}',
    'player.devKnights': 'dev: {dev} · knights: {knights}',
    'player.roadBadge': '🛣️ Road',
    'player.armyBadge': '⚔️ Army',
    'hand.dev': 'dev: {list}',

    'res.wood': 'wood',
    'res.brick': 'brick',
    'res.sheep': 'sheep',
    'res.wheat': 'wheat',
    'res.ore': 'ore',

    'devtype.knight': 'Knight',
    'devtype.victory': 'Victory Point',
    'devtype.roadBuilding': 'Road Building',
    'devtype.yearOfPlenty': 'Year of Plenty',
    'devtype.monopoly': 'Monopoly',

    'discard.title': 'Discard {count} cards',
    'discard.have': '{res} (have {n})',
    'discard.confirm': 'Discard ({chosen}/{count})',

    'robber.stealFrom': 'Steal from?',
    'robber.nobody': 'Nobody',

    'dev.title': 'Play a development card',
    'dev.knight': 'Knight (move robber)',
    'dev.roadBuilding': 'Road Building (2 free roads)',
    'dev.monopoly': 'Monopoly:',
    'dev.yearOfPlenty': 'Year of Plenty (pick 2):',
    'dev.chosen': 'chosen: {list}',
    'dev.cancel': 'Cancel',

    'trade.title': 'Trade',
    'trade.bankPort': 'Bank / Port',
    'trade.give': 'give {ratio} {res}',
    'trade.receive': 'receive:',
    'trade.offerPlayer': 'Offer a player',
    'trade.to': 'to:',
    'trade.youGive': 'You give',
    'trade.youWant': 'You want',
    'trade.sendOffer': 'Send offer',
    'trade.close': 'Close',

    'info.victoryTitle': '🏆 Victory — {vp}/10 VP',
    'info.victoryBody': 'First to 10 VP on their own turn wins.',
    'info.vpSources': 'Settlement 1 · City 2 · VP card 1 · Longest Road 2 (5+ road) · Largest Army 2 (3+ knights).',
    'info.tipsTitle': '💡 Tips',
    'info.opponentsTitle': '👁 Opponents (public info)',
    'info.cardsLine': '{cards} cards · {dev} dev · {knights} knights',
    'info.makes': 'makes: {list}',
    'info.hiddenNote': 'Exact hands stay hidden — only counts & what they produce are shown.',
    'info.reference': '📖 Reference',
    'info.buildCosts': 'Build costs',
    'info.costsBody': '🛣️ Road = 🌲+🧱\n🏠 Settlement = 🌲+🧱+🐑+🌾\n🏙️ City = 3⛰️+2🌾 (upgrades a settlement)\n🃏 Dev card = ⛰️+🐑+🌾',
    'info.diceOdds': 'Dice odds',
    'info.diceBody': '6 & 8 roll most (5/36 each) · 7 = robber (6/36) · 2 & 12 rarest (1/36).',
    'info.strategy': 'Strategy',
    'info.strategyBody': '· Diversify resources; aim for ore+wheat to reach cities.\n· A port (2:1 / 3:1) turns a surplus resource into anything.\n· On a 7, move the robber onto the leader’s best hex and steal from them.\n· A dev card can’t be played the turn you buy it (except a VP card that wins).\n· Keep your hand at 7 or fewer to dodge the 7-discard.',

    'tip.setup1': 'Place on intersections touching high-roll numbers (6 & 8 are most likely) and varied resources.',
    'tip.setup2': 'Your SECOND settlement grants one card per adjacent hex — favor strong spots there.',
    'tip.discard': '⚠️ You hold {cards} cards — a rolled 7 makes you discard {n}. Spend or trade down.',
    'tip.canCity': 'You can upgrade a settlement to a city (+1 VP, double its production).',
    'tip.canSettlement': 'You can build a settlement (+1 VP) on a spot touching your road.',
    'tip.canDev': 'You can buy a development card (Knight, Victory Point, or a progress card).',
    'tip.knightClaim': 'Play 1 more Knight to claim Largest Army (+2 VP).',
    'tip.knightSeize': 'Play 1 more Knight to seize Largest Army (+2 VP).',
    'tip.longestRoad': 'One more connected road could earn Longest Road (need the longest, 5+).',
    'tip.missing': 'You produce no {list}. Trade for it or build toward a matching port.',
    'tip.default': 'Roll, then trade and build. First to 10 VP wins.',

    'lang.label': 'Language',
    'settings.title': 'Settings',
    'settings.speed': 'AI speed',
    'settings.sound': 'Sound',
    'tab.board': 'Board',
    'tab.players': 'Players',
    'tab.info': 'Info',
  },
  ko: {
    'newgame.title': 'Hexland — 새 게임',
    'newgame.disclaimer': '비공식 팬 프로젝트입니다. Catan GmbH / Catan Studio와 무관하며 후원받지 않았습니다.',
    'newgame.aiOpponents': 'AI 상대:',
    'newgame.difficulty': '난이도:',
    'diff.easy': '쉬움',
    'diff.medium': '보통',
    'diff.hard': '어려움',
    'diff.impossible': '불가능',
    'newgame.seed': '시드:',
    'newgame.start': '시작',

    'action.roll': '🎲 주사위',
    'action.road': '길',
    'action.settlement': '정착지',
    'action.city': '도시',
    'action.buyDev': '개발카드 구매',
    'action.playDev': '개발카드 사용',
    'action.trade': '교역',
    'action.endTurn': '턴 종료',

    'app.newGame': '↩ 새 게임',
    'app.setupSettlement': '셋업: 정착지를 놓으세요 (강조된 위치 클릭).',
    'app.setupRoad': '셋업: 길을 놓으세요 (강조된 위치 클릭).',
    'app.moveRobber': '도둑 이동: 강조된 헥스를 클릭하세요.',
    'app.tradeOffer': '{name}이(가) 교역을 제안했습니다.',
    'app.accept': '수락',
    'app.decline': '거절',
    'app.wins': '{name} 승리! 🏆',
    'app.playAgain': '새 게임',

    'player.you': '나',
    'player.ai': 'AI {n}',
    'player.vp': '{n}점',
    'player.cards': '카드: {n}',
    'player.devKnights': '개발: {dev} · 기사: {knights}',
    'player.roadBadge': '🛣️ 최장로',
    'player.armyBadge': '⚔️ 기사단',
    'hand.dev': '개발: {list}',

    'res.wood': '나무',
    'res.brick': '벽돌',
    'res.sheep': '양',
    'res.wheat': '밀',
    'res.ore': '광물',

    'devtype.knight': '기사',
    'devtype.victory': '승점',
    'devtype.roadBuilding': '도로 건설',
    'devtype.yearOfPlenty': '풍년',
    'devtype.monopoly': '독점',

    'discard.title': '카드 {count}장 버리기',
    'discard.have': '{res} (보유 {n})',
    'discard.confirm': '버리기 ({chosen}/{count})',

    'robber.stealFrom': '누구한테서 훔칠까요?',
    'robber.nobody': '안 훔침',

    'dev.title': '개발카드 사용',
    'dev.knight': '기사 (도둑 이동)',
    'dev.roadBuilding': '도로 건설 (무료 길 2개)',
    'dev.monopoly': '독점:',
    'dev.yearOfPlenty': '풍년 (2개 선택):',
    'dev.chosen': '선택: {list}',
    'dev.cancel': '취소',

    'trade.title': '교역',
    'trade.bankPort': '은행 / 항구',
    'trade.give': '{res} {ratio}개 내기',
    'trade.receive': '받기:',
    'trade.offerPlayer': '플레이어에게 제안',
    'trade.to': '대상:',
    'trade.youGive': '내가 줄 것',
    'trade.youWant': '내가 받을 것',
    'trade.sendOffer': '제안 보내기',
    'trade.close': '닫기',

    'info.victoryTitle': '🏆 승리 — {vp}/10점',
    'info.victoryBody': '자기 턴에 먼저 10점에 도달하면 승리.',
    'info.vpSources': '정착지 1 · 도시 2 · 승점카드 1 · 가장 긴 길 2 (길 5+) · 최대 기사단 2 (기사 3+).',
    'info.tipsTitle': '💡 팁',
    'info.opponentsTitle': '👁 상대 (공개 정보)',
    'info.cardsLine': '카드 {cards} · 개발 {dev} · 기사 {knights}',
    'info.makes': '생산: {list}',
    'info.hiddenNote': '정확한 손패는 숨김 — 개수와 생산 자원만 표시됩니다.',
    'info.reference': '📖 참고',
    'info.buildCosts': '건설 비용',
    'info.costsBody': '🛣️ 길 = 🌲+🧱\n🏠 정착지 = 🌲+🧱+🐑+🌾\n🏙️ 도시 = 3⛰️+2🌾 (정착지 업그레이드)\n🃏 개발카드 = ⛰️+🐑+🌾',
    'info.diceOdds': '주사위 확률',
    'info.diceBody': '6·8 가장 자주(각 5/36) · 7 = 도둑(6/36) · 2·12 가장 드묾(1/36).',
    'info.strategy': '전략',
    'info.strategyBody': '· 자원을 다양화하고, 도시를 위해 광물+밀을 노리세요.\n· 항구(2:1 / 3:1)는 남는 자원을 원하는 것으로 바꿔줍니다.\n· 7이 나오면 도둑을 선두의 좋은 헥스로 옮기고 그에게서 훔치세요.\n· 개발카드는 산 턴에 쓸 수 없습니다(승리하는 승점카드 제외).\n· 손패를 7장 이하로 유지해 7 버리기를 피하세요.',

    'tip.setup1': '주사위가 잘 나오는 숫자(6·8이 최빈)와 다양한 자원이 닿는 교차점에 놓으세요.',
    'tip.setup2': '두 번째 정착지는 인접 헥스마다 카드 1장을 줍니다 — 좋은 자리에 놓으세요.',
    'tip.discard': '⚠️ 카드 {cards}장 보유 — 7이 나오면 {n}장을 버립니다. 쓰거나 교역하세요.',
    'tip.canCity': '정착지를 도시로 업그레이드할 수 있습니다(+1점, 생산 2배).',
    'tip.canSettlement': '길에 닿은 자리에 정착지를 지을 수 있습니다(+1점).',
    'tip.canDev': '개발카드를 살 수 있습니다(기사, 승점, 진행 카드).',
    'tip.knightClaim': '기사 1개 더 사용하면 최대 기사단 획득(+2점).',
    'tip.knightSeize': '기사 1개 더 사용하면 최대 기사단 탈취(+2점).',
    'tip.longestRoad': '연결된 길 1개 더면 가장 긴 길 획득 가능(최장 5+ 필요).',
    'tip.missing': '{list}을(를) 생산하지 못합니다. 교역하거나 해당 항구로 향하세요.',
    'tip.default': '주사위를 굴린 뒤 교역·건설하세요. 먼저 10점이면 승리.',

    'lang.label': '언어',
    'settings.title': '설정',
    'settings.speed': 'AI 속도',
    'settings.sound': '소리',
    'tab.board': '보드',
    'tab.players': '플레이어',
    'tab.info': '정보',
  },
};

function interpolate(s: string, params?: Params): string {
  if (!params) return s;
  return s.replace(/\{(\w+)\}/g, (_, k) => (k in params ? String(params[k]) : `{${k}}`));
}

export function translate(lang: Lang, key: string, params?: Params): string {
  const s = dict[lang][key] ?? dict.en[key] ?? key;
  return interpolate(s, params);
}

export function detectLang(): Lang {
  try {
    const stored = typeof localStorage !== 'undefined' ? localStorage.getItem('catan.lang') : null;
    if (stored === 'en' || stored === 'ko') return stored;
    if (typeof navigator !== 'undefined' && navigator.language?.toLowerCase().startsWith('ko')) return 'ko';
  } catch { /* SSR / sandboxed: fall through */ }
  return 'en';
}

export type TFn = (key: string, params?: Params) => string;
interface I18n { lang: Lang; setLang: (l: Lang) => void; t: TFn; }

// Default context works WITHOUT a provider (English) so server-rendered tests
// and any unwrapped render still produce valid output.
const I18nContext = createContext<I18n>({
  lang: 'en',
  setLang: () => {},
  t: (k, p) => translate('en', k, p),
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(detectLang);
  const setLang = (l: Lang) => {
    setLangState(l);
    try { if (typeof localStorage !== 'undefined') localStorage.setItem('catan.lang', l); } catch { /* ignore */ }
  };
  const t: TFn = (key, params) => translate(lang, key, params);
  return createElement(I18nContext.Provider, { value: { lang, setLang, t } }, children);
}

export function useI18n(): I18n {
  return useContext(I18nContext);
}

// Translate a resource name and an engine-assigned player name (You / AI N).
export const tRes = (t: TFn, r: Resource): string => t('res.' + r);
export function displayName(t: TFn, name: string): string {
  if (name === 'You') return t('player.you');
  const m = name.match(/^AI (\d+)$/);
  return m ? t('player.ai', { n: m[1]! }) : name;
}
